{
    'TimePeriods': 'Year-To-Year',
        'StartYear': '2018',
        'EndYear': '2020', 
        'FirstMonth': 0, 
        'LastMonth': 0, 
        'IncludeYTD': 'No', 
        'initialAmount': '2000', 
        'CashFlows': '不投入也不領出', 
        'ContributionAmount': '', 
        'ContributionFrequency': '', 
        'Rebalancing': 'No', 
        'ReinvestDividends': 'No', 
        'DisplayIncome': 'No', 
        'Portfolios': [{'StockID': '2330', 'part': [50, 30, 0]}, 
                       {'StockID': '0050', 'part': [50, 70, 0]}, 
                       {'StockID': '', 'part': [0, 0, 0]}, 
                       {'StockID': '', 'part': [0, 0, 0]}, 
                       {'StockID': '', 'part': [0, 0, 0]}]
}